---
name: test
on:
  pull_request:
    branches: ["main"]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install package.
        run: pip install -e .
      - name: Install test dependencies.
        run: pip install pytest
      - name: Run the tests
        run: pytest
  build:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install package.
        run: pip install .
      - name: Build the test site.
        run: aep-site-gen tests/test_data/ /out/
  lint:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v3
      # versions of linters should be hard-pinned
      # to ensure no random breakages to styling.
      - name: Install linters.
        run: pip install flake8==6.1.0 black==23.9.1
      - name: Run flake8
        run: flake8 aep_site/ tests/
      - name: Run .black
        run: black . --check
  mypy:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v3
      - name: Install package.
        run: pip install .
      - name: Install mypy.
        run: pip install mypy
      - name: Run mypy.
        run: mypy aep_site
